version: '3'
services:
  php:
    build:
      context: .
      dockerfile: docker/Php.Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: docktrine
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: docktrine
      MYSQL_ROOT_PASSWORD: root

  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
